version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:11.0'

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          executor: jdk
#      - build:
#          context: SonarCloud